version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: TestEmailSendler_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   db
        container_name: TestEmailSendler_app

    db:
        image: mysql
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: TestEmailSendler
            MYSQL_ROOT_PASSWORD: root
        ports:
            -  "8101:3306"
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
    npm:
        image: node
        container_name: TestEmailSendler_node
        volumes:
            -   ./:/var/www/
        entrypoint: /bin/bash
        ports:
            -   8000:8000
        working_dir: /var/www/
        tty: true

    adminer:
        image: adminer
        container_name: TestEmailSendler_adminer
        ports:
            -   6330:8080
